### ISSUE TITLE
Field 'id' expected a number but got 'admin'

### ISSUE THREAD

**Issue by VunkLai** [LeoTunero/first_side_project#17]
```
ValueError at /admin
Field 'id' expected a number but got 'admin'.
...
```

This is the `urls.py` issue.

**Comment by VunkLai** [comment]
Full logs

```
[09/Aug/2021 23:30:25] "GET /favicon.ico HTTP/1.1" 500 131214
[09/Aug/2021 23:30:28] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2218
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'favicon.ico'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/views/generic/detail.py", line 106, in get
    self.object = self.get_object()
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/views/generic/detail.py", line 36, in get_object
    queryset = queryset.filter(pk=pk)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/vunk/.local/share/virtualenvs/sharky-TN6XH1O4/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'favicon.ico'.
[09/Aug/2021 23:30:28] "GET /favicon.ico HTTP/1.1" 500 131479
```
